## by Denzel Code
---
name: JoinItems
main: JoinItems\Main
author: Denzel Code
version: 1.0.0
api: [3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12]
commands:
    ji:
        description: Join Items command.
    joinitems:
        description: Join Items command.
permissions:
    joinitems.perm:
        default: op
        description: JoinItems Permission. 
    joinitems.allowplace:
        default: op
        description: JoinItems AllowPlace Permission. 
...
